# Generated by Django 5.2.8 on 2025-11-21 23:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'catalog_item',
            },
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'taxonomies',
                'db_table': 'taxonomy',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user_account',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AppGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_group',
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('item_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rules', models.JSONField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='core.appgroup')),
            ],
            options={
                'db_table': 'decision',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='core.decision')),
            ],
            options={
                'db_table': 'conversation',
            },
        ),
        migrations.CreateModel(
            name='DecisionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('external_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_items', to='core.catalogitem')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.decision')),
            ],
            options={
                'db_table': 'decision_item',
            },
        ),
        migrations.CreateModel(
            name='DecisionSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='core.decision')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='core.decisionitem')),
            ],
            options={
                'db_table': 'decision_selection',
            },
        ),
        migrations.CreateModel(
            name='DecisionSharedGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_groups', to='core.decision')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_decisions', to='core.appgroup')),
            ],
            options={
                'db_table': 'decision_shared_group',
            },
        ),
        migrations.CreateModel(
            name='DecisionVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_like', models.BooleanField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('note', models.TextField(blank=True, null=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.decisionitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decision_vote',
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=50)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.appgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_membership',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('scope', models.CharField(choices=[('global', 'Global'), ('item_type', 'Item Type'), ('decision', 'Decision'), ('group', 'Group')], max_length=50)),
                ('item_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'question',
                'indexes': [models.Index(fields=['scope'], name='question_scope_284889_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('order_num', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='core.question')),
            ],
            options={
                'db_table': 'answer_option',
                'ordering': ['order_num'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.taxonomy')),
            ],
            options={
                'db_table': 'term',
            },
        ),
        migrations.CreateModel(
            name='DecisionItemTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_terms', to='core.decisionitem')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_terms', to='core.term')),
            ],
            options={
                'db_table': 'decision_item_term',
            },
        ),
        migrations.CreateModel(
            name='CatalogItemTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_terms', to='core.catalogitem')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_terms', to='core.term')),
            ],
            options={
                'db_table': 'catalog_item_term',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_value', models.JSONField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('answer_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_answers', to='core.answeroption')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='core.decision')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='core.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_answer',
            },
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['group'], name='decision_group_i_609219_idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['status'], name='decision_status_d81f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionitem',
            index=models.Index(fields=['decision'], name='decision_it_decisio_37db97_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionitem',
            index=models.Index(fields=['catalog_item'], name='decision_it_catalog_c27d08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='decisionitem',
            unique_together={('decision', 'external_ref', 'label')},
        ),
        migrations.AddIndex(
            model_name='decisionselection',
            index=models.Index(fields=['decision'], name='decision_se_decisio_5ae646_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionselection',
            index=models.Index(fields=['item'], name='decision_se_item_id_b96de8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='decisionselection',
            unique_together={('decision', 'item')},
        ),
        migrations.AddIndex(
            model_name='decisionsharedgroup',
            index=models.Index(fields=['decision'], name='decision_sh_decisio_b91fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionsharedgroup',
            index=models.Index(fields=['group'], name='decision_sh_group_i_69a14b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='decisionsharedgroup',
            unique_together={('decision', 'group')},
        ),
        migrations.AddIndex(
            model_name='decisionvote',
            index=models.Index(fields=['item'], name='decision_vo_item_id_89527c_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionvote',
            index=models.Index(fields=['user'], name='decision_vo_user_id_48a8f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='decisionvote',
            unique_together={('user', 'item')},
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'is_confirmed'], name='group_membe_group_i_af8718_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sent_at'], name='message_convers_34c8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='message_sender__0e912c_idx'),
        ),
        migrations.AddIndex(
            model_name='answeroption',
            index=models.Index(fields=['question'], name='answer_opti_questio_998384_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['taxonomy'], name='term_taxonom_b44977_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('taxonomy', 'value')},
        ),
        migrations.AddIndex(
            model_name='decisionitemterm',
            index=models.Index(fields=['item'], name='decision_it_item_id_ffd0b6_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionitemterm',
            index=models.Index(fields=['term'], name='decision_it_term_id_be16ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='decisionitemterm',
            unique_together={('item', 'term')},
        ),
        migrations.AddIndex(
            model_name='catalogitemterm',
            index=models.Index(fields=['catalog_item'], name='catalog_ite_catalog_4f168a_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitemterm',
            index=models.Index(fields=['term'], name='catalog_ite_term_id_161747_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogitemterm',
            unique_together={('catalog_item', 'term')},
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user'], name='user_answer_user_id_bf874f_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['question'], name='user_answer_questio_47cb98_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['decision'], name='user_answer_decisio_b1b142_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user', 'question', 'decision')},
        ),
    ]
