# Generated by Django 5.2.8 on 2025-11-22 00:19

from django.db import migrations
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_approval_trigger'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS decision_item_attributes_gin_idx 
                ON decision_item USING GIN (attributes);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS decision_item_attributes_gin_idx;
            """
        ),
    ]
