# Generated by Django 5.2.8 on 2025-11-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_gin_index_to_decision_item'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='decisionvote',
            constraint=models.CheckConstraint(condition=models.Q(('is_like__isnull', True), ('rating__isnull', True), _negated=True), name='vote_requires_is_like_or_rating'),
        ),
    ]
