# Generated by Django 5.2.8 on 2025-11-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_membership_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='group_membe_group_i_990501_idx',
            old_name='core_groupm_group_i_status_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='group_membe_user_id_ce33d8_idx',
            old_name='core_groupm_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='group_membe_members_0218b2_idx',
            old_name='core_groupm_members_status_idx',
        ),
    ]
