# Generated by Django 5.2.8 on 2025-12-13 20:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_core_groupm_group_i_status_idx_group_membe_group_i_990501_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parameters', models.JSONField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='core.decisionitem')),
            ],
            options={
                'db_table': 'generation_job',
                'indexes': [models.Index(fields=['item'], name='generation__item_id_af519d_idx'), models.Index(fields=['status'], name='generation__status_d17c83_idx'), models.Index(fields=['request_id'], name='generation__request_4a231e_idx'), models.Index(fields=['created_at'], name='generation__created_c12cef_idx')],
            },
        ),
    ]
