# Generated by Django 5.2.8 on 2025-12-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_generation_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
