# Generated by Django 5.2.8 on 2025-12-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_increase_image_url_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
